#!/usr/bin/env pwsh
<#
.SYNOPSIS
    Pre-commit cleanup script for TTS Demo Tool project
    
.DESCRIPTION
    Scans for temporary files, test results, and untracked files.
    Offers to add them to .gitignore or delete them before commit.
    
.PARAMETER DryRun
    Show what would be done without making changes
    
.PARAMETER Auto
    Automatically handle all temporary files without prompting
    
.EXAMPLE
    .\cleanup-before-commit.ps1
    Interactive mode - prompts for each file category
    
.EXAMPLE
    .\cleanup-before-commit.ps1 -DryRun
    Show what would be done without making changes
    
.EXAMPLE
    .\cleanup-before-commit.ps1 -Auto
    Automatically clean all temporary files
#>

param(
    [switch]$DryRun,
    [switch]$Auto
)

$ErrorActionPreference = "Stop"
$scriptRoot = Split-Path -Parent $MyInvocation.MyCommand.Path
$projectRoot = $scriptRoot
$demoToolRoot = Join-Path $projectRoot "demo-tool"

Write-Host "`n=============================================================" -ForegroundColor Cyan
Write-Host "       Pre-Commit Cleanup - TTS Demo Tool              " -ForegroundColor Cyan
Write-Host "=============================================================`n" -ForegroundColor Cyan

if ($DryRun) {
    Write-Host "[DRY RUN MODE] No files will be modified or deleted`n" -ForegroundColor Yellow
}

# Define temporary file patterns
$tempPatterns = @{
    "JMeter Logs" = @{
        Path = "demo-tool"
        Include = @("jmeter.log", "jmeter_*.log")
        Recurse = $true
        ShouldDelete = $true
        Reason = "Generated by JMeter during test execution"
    }
    "JTL Test Results" = @{
        Path = "demo-tool\logs"
        Include = @("log_*.jtl", "test_*.jtl")
        Exclude = @("phase1_success_baseline.jtl")  # Keep baseline
        Recurse = $false
        ShouldDelete = $false
        AddToGitignore = $true
        Reason = "Test result files - keep recent, add logs/ to .gitignore"
    }
    "Application Logs" = @{
        Path = "demo-tool\logs"
        Include = @("*.log")
        Recurse = $false
        ShouldDelete = $false
        AddToGitignore = $true
        Reason = "Application log files - add logs/ to .gitignore"
    }
    "Maven Build Artifacts" = @{
        Path = "demo-tool\target"
        Include = @("*")
        Recurse = $true
        ShouldDelete = $true
        AddToGitignore = $true
        Reason = "Maven build output - should be in .gitignore"
    }
    "JMX Test Artifacts" = @{
        Path = "demo-tool\src\main\resources\jmx"
        Include = @("*.log", "*.jtl")
        Recurse = $false
        ShouldDelete = $true
        Reason = "Test artifacts in source tree - should be deleted"
    }
    "Temp/Backup Files" = @{
        Path = "demo-tool"
        Include = @("*.tmp", "*.temp", "*.bak", "*~")
        Recurse = $true
        ShouldDelete = $true
        Reason = "Temporary and backup files"
    }
}

# Define files to keep (validation/integration tests)
$keepPatterns = @(
    "test-*.ps1",
    "verify-*.ps1",
    "quick-start.ps1",
    "kill-stray-gui.ps1"
)

# Track actions
$deleteCount = 0
$gitignoreEntries = @()
$keptFiles = @()

# Function to add entry to .gitignore if not present
function Add-ToGitignore {
    param([string]$Entry)
    
    $gitignorePath = Join-Path $projectRoot ".gitignore"
    
    if (-not (Test-Path $gitignorePath)) {
        Write-Host "  [WARN] .gitignore not found, creating..." -ForegroundColor Yellow
        if (-not $DryRun) {
            New-Item -Path $gitignorePath -ItemType File -Force | Out-Null
        }
    }
    
    $content = Get-Content $gitignorePath -ErrorAction SilentlyContinue
    $normalized = $Entry.Replace('\', '/')
    
    if ($content -notcontains $normalized -and $content -notcontains $Entry) {
        if (-not $DryRun) {
            Add-Content -Path $gitignorePath -Value $normalized
        }
        return $true
    }
    return $false
}

# Process each category
foreach ($category in $tempPatterns.Keys) {
    $config = $tempPatterns[$category]
    $searchPath = Join-Path $projectRoot $config.Path
    
    if (-not (Test-Path $searchPath)) {
        continue
    }
    
    Write-Host "═══ $category ═══" -ForegroundColor Yellow
    Write-Host "  Path: $($config.Path)" -ForegroundColor Gray
    Write-Host "  Reason: $($config.Reason)" -ForegroundColor Gray
    
    $files = @()
    foreach ($pattern in $config.Include) {
        $findParams = @{
            Path = $searchPath
            Filter = $pattern
            Recurse = $config.Recurse
            File = $true
            ErrorAction = "SilentlyContinue"
        }
        $foundFiles = Get-ChildItem @findParams
        
        # Apply exclusions
        if ($config.Exclude) {
            $foundFiles = $foundFiles | Where-Object { 
                $name = $_.Name
                $config.Exclude | ForEach-Object { $name -notlike $_ } | Where-Object { $_ -eq $true }
            }
        }
        
        $files += $foundFiles
    }
    
    if ($files.Count -eq 0) {
        Write-Host "  [OK] No files found" -ForegroundColor Green
        Write-Host ""
        continue
    }
    
    Write-Host "  Found $($files.Count) file(s)" -ForegroundColor Cyan
    
    # Show sample files (max 5)
    $samples = $files | Select-Object -First 5
    foreach ($file in $samples) {
        $relPath = $file.FullName.Replace($projectRoot, "").TrimStart('\')
        Write-Host "    - $relPath" -ForegroundColor Gray
    }
    if ($files.Count -gt 5) {
        Write-Host "    ... and $($files.Count - 5) more" -ForegroundColor Gray
    }
    
    # Decide action
    $action = "skip"
    
    if ($Auto) {
        if ($config.ShouldDelete) {
            $action = "delete"
        } elseif ($config.AddToGitignore) {
            $action = "ignore"
        }
    } else {
        Write-Host "`n  What should we do with these files?" -ForegroundColor White
        if ($config.ShouldDelete) {
            Write-Host "    [D] Delete all (recommended)" -ForegroundColor Yellow
        }
        if ($config.AddToGitignore) {
            Write-Host "    [I] Add directory to .gitignore and keep files" -ForegroundColor Yellow
        }
        Write-Host "    [K] Keep as-is (no action)" -ForegroundColor Gray
        Write-Host "    [S] Skip (same as Keep)" -ForegroundColor Gray
        
        $response = Read-Host "  Choice"
        
        switch ($response.ToLower()) {
            "d" { $action = "delete" }
            "i" { $action = "ignore" }
            "k" { $action = "skip" }
            "s" { $action = "skip" }
            default { $action = "skip" }
        }
    }
    
    # Execute action
    switch ($action) {
        "delete" {
            Write-Host "  [DELETE] Removing $($files.Count) file(s)..." -ForegroundColor Red
            if (-not $DryRun) {
                foreach ($file in $files) {
                    Remove-Item $file.FullName -Force
                    $deleteCount++
                }
            } else {
                $deleteCount += $files.Count
            }
        }
        "ignore" {
            $gitignoreEntry = $config.Path.Replace('\', '/') + "/"
            Write-Host "  [GITIGNORE] Adding '$gitignoreEntry' to .gitignore..." -ForegroundColor Blue
            if (Add-ToGitignore $gitignoreEntry) {
                $gitignoreEntries += $gitignoreEntry
            }
            $keptFiles += $files
        }
        "skip" {
            Write-Host "  [SKIP] Keeping files as-is" -ForegroundColor Gray
            $keptFiles += $files
        }
    }
    
    Write-Host ""
}

# Check for untracked files in git (if git is initialized)
if (Test-Path (Join-Path $projectRoot ".git")) {
    Write-Host "═══ Git Untracked Files ═══" -ForegroundColor Yellow
    
    Push-Location $projectRoot
    $untrackedFiles = git ls-files --others --exclude-standard 2>$null
    Pop-Location
    
    if ($untrackedFiles) {
        $untrackedCount = ($untrackedFiles | Measure-Object).Count
        Write-Host "  Found $untrackedCount untracked file(s)" -ForegroundColor Cyan
        
        $samples = $untrackedFiles | Select-Object -First 10
        foreach ($file in $samples) {
            Write-Host "    - $file" -ForegroundColor Gray
        }
        if ($untrackedCount -gt 10) {
            Write-Host "    ... and $($untrackedCount - 10) more" -ForegroundColor Gray
        }
        
        Write-Host "`n  Tip: Review these files before committing" -ForegroundColor Yellow
        Write-Host "       Use 'git add <file>' or add to .gitignore" -ForegroundColor Gray
    } else {
        Write-Host "  [OK] No untracked files" -ForegroundColor Green
    }
    Write-Host ""
}

# Summary
Write-Host "=============================================================" -ForegroundColor Cyan
Write-Host "                    Cleanup Summary                     " -ForegroundColor Cyan
Write-Host "=============================================================" -ForegroundColor Cyan
Write-Host ""

if ($DryRun) {
    Write-Host "  [DRY RUN] Actions that WOULD be taken:" -ForegroundColor Yellow
} else {
    Write-Host "  Actions taken:" -ForegroundColor Green
}

Write-Host "    Files deleted: $deleteCount" -ForegroundColor $(if($deleteCount -gt 0){"Red"}else{"Gray"})
Write-Host "    .gitignore entries added: $($gitignoreEntries.Count)" -ForegroundColor $(if($gitignoreEntries.Count -gt 0){"Blue"}else{"Gray"})
Write-Host "    Files kept: $($keptFiles.Count)" -ForegroundColor Gray

if ($gitignoreEntries.Count -gt 0) {
    Write-Host "`n  New .gitignore entries:" -ForegroundColor Blue
    foreach ($entry in $gitignoreEntries) {
        Write-Host "    + $entry" -ForegroundColor Blue
    }
}

Write-Host ""

# Final recommendations
Write-Host "Recommendations:" -ForegroundColor Cyan
Write-Host "  1. Review changes before committing" -ForegroundColor White
Write-Host "  2. Test scripts (test-*.ps1) are kept - they're validation tools" -ForegroundColor White
Write-Host "  3. Run 'git status' to see what will be committed" -ForegroundColor White
Write-Host "  4. Keep phase1_success_baseline.jtl as reference data" -ForegroundColor White
Write-Host ""

if (-not $DryRun -and -not (Test-Path (Join-Path $projectRoot ".git"))) {
    Write-Host "[WARN] Git repository not initialized yet" -ForegroundColor Yellow
    Write-Host "  Run: git init" -ForegroundColor Gray
    Write-Host "  Then: git add ." -ForegroundColor Gray
    Write-Host "       git commit -m 'Initial commit'" -ForegroundColor Gray
    Write-Host ""
}

Write-Host "[OK] Cleanup complete!" -ForegroundColor Green
Write-Host ""
